version: '2'
services:
    mysql:
      image: mysql:5.7
      volumes: 
        - "/datadrive/prestadb:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: prestashop
    php-fpm:
      build: "./docker-prestashop-php"
      volumes:
        - "/datadrive/www/prestashop:/src"
    nginx:
      build: "./docker-prestashop-nginx"
      environment: 
        PHP_HOST: "php-fpm"
        CERTIFICATE_PATH:
        CERTIFICATE_KEY_PATH:
      volumes:
        - "/datadrive/www/prestashop:/src"
        - "/datadrive/ssl:/ssl"
      ports:
        - "80:80"
        - "443:443"

