version: '2'
services:
    mysql:
      image: mysql:5.7
      volumes: 
        - "/datadrive/prestadb:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: prestashop
    php-fpm:
      build: "../docker-prestashop-php"
      volumes:
        - "/datadrive/prestashop:/src"
    nginx:
      build: "../docker-prestashop-nginx"
      environment: 
        PHP_HOST: php-fpm
      volumes:
        - "/datadrive/prestashop:/src"
      ports:
        - "80:80"
        - "443:443"

